### ISSUE TITLE
Screen selector bug

### ISSUE THREAD

**Issue by TeamDman** [PhantomOwl404/Desktop-Awoo#11]
![image](https://user-images.githubusercontent.com/9356891/56394070-2a43fa00-6204-11e9-8c6c-3ff24ff06f45.png)
Similiar to #4 
Might be related to the new drag mechanic

**Comment by PhantomOwl404** [comment]
Turn out I commented it and was testing out things. Ill try fix quickly all three new issues by the next hour
![EEEEEEE](https://user-images.githubusercontent.com/48143117/56397087-36ce4f80-6210-11e9-832c-15c97fdc9277.PNG)

**Comment by PhantomOwl404** [comment]
new update aviable

**Comment by PhantomOwl404** [comment]
Problem with whitebox when chanign screen

**Comment by PhantomOwl404** [comment]
hjdsfalakbvbresivdjlsfbsdg

**Comment by PhantomOwl404** [comment]
These monitor issues is going to driving me insane.
It almost a month since the first monitor issue.
I really need to drag awoo with y-axis so i can remove this.
