### ISSUE TITLE
Dragging Momiji to separate monitors causes height discrepancy 

### ISSUE THREAD

**Issue by TeamDman** [PhantomOwl404/Desktop-Awoo#12]
![image](https://user-images.githubusercontent.com/9356891/56394250-b81fe500-6204-11e9-8f4a-064fbaf16dcc.png)
![image](https://user-images.githubusercontent.com/9356891/56394265-c110b680-6204-11e9-9308-5fc46f272f13.png)
![image](https://user-images.githubusercontent.com/9356891/56394276-c8d05b00-6204-11e9-963e-c1c0c107b2d5.png)
I suppose a clean solution that would double as a new feature would be letting you also adjust Momiji's vertical offset when dragging her hand near the edge of a monitor

**Comment by PhantomOwl404** [comment]
I fix the screen detecting problem (again) and cap it to the selected screen

**Comment by PhantomOwl404** [comment]
Thank you so much for your help teamy.
