### ISSUE TITLE
HiDPI monitor seems to cause some display issue

### ISSUE THREAD

**Issue by patrick330602** [PhantomOwl404/Desktop-Awoo#13]
![image](https://user-images.githubusercontent.com/15316889/56402794-5e193100-6291-11e9-99f6-aff66c73d712.png)

The settings page is messed up in a HIDPI Settings. I am using a 3000x2000 monitor with 200% Scaling

**Comment by PhantomOwl404** [comment]
ill look into dpi support

**Comment by PhantomOwl404** [comment]
I think i had just fix it with the new upload

**Comment by patrick330602** [comment]
Thanks! after the update, it does fix the problem
