### ISSUE TITLE
Momiji is in the middle of the screen after changing her size

### ISSUE THREAD

**Issue by Yochyo** [PhantomOwl404/Desktop-Awoo#14]
Momiji is in the middle of the screen after changing her size. Also, the background is not transparent but white and she´s not in the foreground but behaves like a normal window in windows.
![grafik](https://user-images.githubusercontent.com/22239101/56415850-48a30780-628f-11e9-9267-e87437cbcb7b.png)

**Comment by elterrasense** [comment]
Having the same issue.

Sometimes changing the tick-rate fixes it, but I think it only does at large scale. Also restarting the whole program can fix it, but not always.

**Comment by PhantomOwl404** [comment]
Alright i think i found a solution, it has to do with unity's order of event: https://docs.unity3d.com/Manual/ExecutionOrder.html

Ill fix it and upload a new version by tonight

**Comment by PhantomOwl404** [comment]
At least it not a monitor problem otherwise by PTSD from my multi-monitor war will trigger again

**Comment by PhantomOwl404** [comment]
I had just upload a version to fix the issue.
Thank you Yochyo and elterrasense
