### ISSUE TITLE
Add option to launch on windows startup

### ISSUE THREAD

**Issue by TeamDman** [PhantomOwl404/Desktop-Awoo#16]
Would be nice enhancement <3

**Comment by PhantomOwl404** [comment]
It would be nice but im being road blocked by windows permission which means i might have to make it an installer which i really don't want. Ill try to see if i can make a workaround, if not i really can't. 
:(

**Comment by TeamDman** [comment]
There is the `%appdata%\Microsoft\Windows\Start Menu\Programs\Startup` path, you could make the option simply create/destroy a shortcut to the .exe there (that's been my temporary workaround so far.)

**Comment by PhantomOwl404** [comment]
I found another solution that doesn't require extra permission. Thanks teamy for the suggestion
