### ISSUE TITLE
"save" file

### ISSUE THREAD

**Issue by iveykun** [PhantomOwl404/Desktop-Awoo#2]
would be nice to make it rememeber i like the small awoo with a maga hat... basically remember last time's session settings
Possible improvements: more sounds and moveable
invisible window (doesn't display thumbnail and unity at start)
New to github so i'm not sure if this is the right place to post
thanks

**Comment by PhantomOwl404** [comment]
You can always join discord : ZyHAgWQ . 
I will work on saving data. Awoo sound may not be next week but probably the week after. And the only thing prevent me getting rid of unity logo is money for license. XD
