### ISSUE TITLE
Config appearance improvements

### ISSUE THREAD

**Issue by TeamDman** [PhantomOwl404/Desktop-Awoo#27]
The close button has no indicator
![image](https://user-images.githubusercontent.com/9356891/58216146-1b50db80-7ccb-11e9-9ad0-785446141e69.png)
![image](https://user-images.githubusercontent.com/9356891/58216153-27d53400-7ccb-11e9-86c8-3f5e4bcfdc68.png)
Might be related, the gui element seems to be out of the expected area
![image](https://user-images.githubusercontent.com/9356891/58216157-30c60580-7ccb-11e9-959e-bc5330e85e95.png)

Could also use some padding on the scrolling parts
![image](https://user-images.githubusercontent.com/9356891/58216179-5226f180-7ccb-11e9-98c4-58ec9c1bbc0d.png)

**Comment by PhantomOwl404** [comment]
Thanks again Teamy
