### ISSUE TITLE
Persist settings through updates

### ISSUE THREAD

**Issue by TeamDman** [PhantomOwl404/Desktop-Awoo#30]
Would be nice if the `DesktopAwoo_Data/AwooPreferences.xml` was persisted through updates
The main complications would be making sure to have new config values inserted and saved by the runtime when missing, and to make sure that old config values are valid (in case a dropdown list changes kinda thing)

**Comment by PhantomOwl404** [comment]
Thankful i choose XML as data format (made it incredibly future-proof), it shouldnt be too diffucult . Though I do need to change part of 'coreupdater.exe'. Thanks, teamy
