### ISSUE TITLE
gpu

### ISSUE THREAD

**Issue by Kiolli** [PhantomOwl404/Desktop-Awoo#32]
please use GPU for render ^_^

**Comment by PhantomOwl404** [comment]
Can you screenshot your task manager?

**Comment by Kiolli** [comment]
In the previous version he occupied a lot of CPU resources

**Comment by Kiolli** [comment]
And on the expansion of the screen 1400Х900 image is very similar to the quality
![изображение](https://user-images.githubusercontent.com/46153369/59964066-b5938180-950c-11e9-867d-e20833faec04.png)

**Comment by PhantomOwl404** [comment]
DesktopAwoo uses both cpu and gpu. I believe your issue is that its using too much cpu resources. Ill try to reduce cpu usage

**Comment by PhantomOwl404** [comment]
you can try setting the 'tick rate' to '30' to reduce cpu usage
