### ISSUE TITLE
Screen selector only shows primary screen

### ISSUE THREAD

**Issue by TeamDman** [PhantomOwl404/Desktop-Awoo#4]
![](https://i.imgur.com/n5vu2eG.png)

**Comment by PhantomOwl404** [comment]
yea someone else said the same thing. I really thought i fixed it, looks like i have to look into the issue again

**Comment by PhantomOwl404** [comment]
I figured out the issue, it took me while to realize that library is broken and i have to rewrite everything. Update will be on Saturday. result : [img](https://imgur.com/a/plDowNl). Thank you for the feedback~

**Comment by PhantomOwl404** [comment]
Some people with multi monitor still has issue

**Comment by PhantomOwl404** [comment]
Nvm I don't know math. I just fixed it.
