### ISSUE TITLE
Awoo doesn't stop click propogation

### ISSUE THREAD

**Issue by TeamDman** [PhantomOwl404/Desktop-Awoo#5]
Clicks aren't canceled after interacting with Awoo

If fixable, maybe could be a config option, there is merit in allowing it to happen, since the character still draws over games in fullscreen windowed

https://streamable.com/1e75l

**Comment by PhantomOwl404** [comment]
I'll work on a fix for it. thanks for the feedback ~

**Comment by PhantomOwl404** [comment]
I fixed the issue somewhat. The problem will no longer appear if awoo is pin to top however it will still happen if it is pin to back. Therefore I won't close the issue just yet. Updates will be on sateruday

**Comment by PhantomOwl404** [comment]
The issue is fixed,but I can't even remember when it was fixed.

**Comment by PhantomOwl404** [comment]
oh wait nvm
![bugu](https://user-images.githubusercontent.com/48143117/56087818-c6ef4c00-5e40-11e9-8133-c1eefd38acc0.gif)

**Comment by TeamDman** [comment]
Fixed, for me at least.
S1E7
![a0UG9BqElQ](https://user-images.githubusercontent.com/9356891/57584072-60903480-74a5-11e9-84fc-9a286c9249fd.gif)
