### ISSUE TITLE
Right click menu in system tray positions poorly

### ISSUE THREAD

**Issue by TeamDman** [PhantomOwl404/Desktop-Awoo#6]
https://i.imgur.com/rNDCzGd.png

Sometimes the menu doesn't hide when something else is focused instead of clicking an option, then it stays and glitches out, and can't be used, even if the tray is right clicked again
https://i.imgur.com/OA9EShF.png

**Comment by PhantomOwl404** [comment]
Thank you :). You had helped me a lot with testing out awoo. Ill look into the problem.

**Comment by PhantomOwl404** [comment]
I fixed the problem with by making everything else except awoo on another thread  (ie. notification tray and preference menu). Update will be Sateruday. Thank you ~
