### ISSUE TITLE
Awoo settings persist but visuals don't respect them on load

### ISSUE THREAD

**Issue by TeamDman** [PhantomOwl404/Desktop-Awoo#7]
The "Awoo" sound option still works, but the visuals themselves aren't there on load.
https://streamable.com/o66q5

**Comment by PhantomOwl404** [comment]
XD i really need to work on my quality control.

**Comment by TeamDman** [comment]
We are your quality control!

**Comment by PhantomOwl404** [comment]
thank you guys
