### ISSUE TITLE
You can let her awoo several times at the same time

### ISSUE THREAD

**Issue by Yochyo** [PhantomOwl404/Desktop-Awoo#9]
You can let momiji awoo several times in a second at the same time. To recreate it, just click 10 times on her mounth really fast.

**Comment by TeamDman** [comment]
I'd like this to remain as a feature, personally.

**Comment by Yochyo** [comment]
well yeah it sounds funny I guess? ^^

**Comment by PhantomOwl404** [comment]
awawawawooawooawoawooooo

**Comment by PhantomOwl404** [comment]
I had just fixed it
